name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  icons_plus: ^5.0.0
  shared_preferences: ^2.5.2
  http: ^1.3.0
  pinput: ^5.0.1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  grouped_list: ^6.0.0
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  mime: ^2.0.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
    - assets/
    - assets/image/

  uses-material-design: true

